const PERMISSIONS = {
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_EDIT: 'DOCUMENT_EDIT',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',
  DOCUMENT_EXPORT: 'DOCUMENT_EXPORT',

  MEMBER_VIEW: 'MEMBER_VIEW',
  MEMBER_INVITE: 'MEMBER_INVITE',
  MEMBER_REMOVE: 'MEMBER_REMOVE',
  MEMBER_ROLE_UPDATE: 'MEMBER_ROLE_UPDATE',

  COMMENT_CREATE: 'COMMENT_CREATE',
  COMMENT_EDIT: 'COMMENT_EDIT',
  COMMENT_DELETE: 'COMMENT_DELETE',
  COMMENT_RESOLVE: 'COMMENT_RESOLVE',

  TASK_CREATE: 'TASK_CREATE',
  TASK_EDIT: 'TASK_EDIT',
  TASK_ASSIGN: 'TASK_ASSIGN',
  TASK_COMPLETE: 'TASK_COMPLETE',

  SOURCE_VIEW: 'SOURCE_VIEW',
  SOURCE_ADD: 'SOURCE_ADD',
  SOURCE_EDIT: 'SOURCE_EDIT',
  SOURCE_DELETE: 'SOURCE_DELETE',

  AI_RUN: 'AI_RUN',
  AI_CANCEL: 'AI_CANCEL',

  VERSION_VIEW: 'VERSION_VIEW',
  VERSION_CREATE: 'VERSION_CREATE',
  VERSION_RESTORE: 'VERSION_RESTORE',

  CHAT_USE: 'CHAT_USE',

  SETTINGS_VIEW: 'SETTINGS_VIEW',
  SETTINGS_EDIT: 'SETTINGS_EDIT',

  AUDIT_VIEW: 'AUDIT_VIEW',
  OWNER_TRANSFER: 'OWNER_TRANSFER',
};

const ROLE_PERMISSIONS = {
  OWNER: Object.values(PERMISSIONS),

  EDITOR: [
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_EDIT,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_EDIT,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.COMMENT_RESOLVE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.SOURCE_VIEW,
    PERMISSIONS.SOURCE_ADD,
    PERMISSIONS.SOURCE_EDIT,
    PERMISSIONS.AI_RUN,
    PERMISSIONS.VERSION_VIEW,
    PERMISSIONS.VERSION_CREATE,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.AUDIT_VIEW,
  ],

  RESEARCHER: [
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_RESOLVE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.SOURCE_VIEW,
    PERMISSIONS.SOURCE_ADD,
    PERMISSIONS.AI_RUN,
    PERMISSIONS.VERSION_VIEW,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.AUDIT_VIEW,
  ],

  REVIEWER: [
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_RESOLVE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.SOURCE_VIEW,
    PERMISSIONS.VERSION_VIEW,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.AUDIT_VIEW,
  ],

  VIEWER: [
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_EXPORT,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.SOURCE_VIEW,
    PERMISSIONS.VERSION_VIEW,
    PERMISSIONS.CHAT_USE,
  ],
};

function hasPermission(role, permission) {
  if (!role || !ROLE_PERMISSIONS[role]) return false;
  return ROLE_PERMISSIONS[role].includes(permission);
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
};
